name: helloworld
description: Dart gRPC sample client and server using brotli, lz4, zstd (ZStandard) compression.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  es_compression_grpc:
    path: ../../

dev_dependencies:
  pedantic: ^1.9.0
